### ISSUE TITLE
Proper handling of version byte

### ISSUE THREAD

**Issue by martinhanzik** [demipixel/factorio-blueprint#11]
The first byte determines the format of the blueprint string, currently the only version is '0' which uses zlib deflate and base64. No other formats exist (yet), but I will probably try to add a more compact version, using a higher base encoding and better compression. Better be safe than sorry.

**Comment by demipixel** [comment]
I'll probably add this when the time comes. Unlike for old blueprint strings, I'll probably keep support for previous versions (and encode will take an optional parameter to export to an older version).

**Comment by demipixel** [comment]
Was going to close this thinking "This is never gonna change" until I looked at the author and reread the post.

Resolved (after a few months)!
