### ISSUE TITLE
Setting to include roboports, logistic chests and repair packs

### ISSUE THREAD

**Issue by tomato42** [demipixel/factorio-blueprint#12]
One problem with outposts is that sometimes biters/spitters get to the walls/turrets and damage them, slowly tearing down the outpost.

I'd like to see:
 * ability to add enough roboports to cover the whole outpost
 * storage chests so that outpost can be remotely disassembled when the ore is used up
 * filter inserter to extract repair packs/turrets/walls/ammo from the train to a passive provider set up to connect to network and extracting only when not enough stuff is available
 * auto insertion of ammo to gun turrets (if used)

While the addition of roboports manually after placing the blueprint is easy enough, the setup of the providers is a bit of a chore.

Maybe also automatic insertion of construction bots to a roboport when there are too few, or some got destroyed?

**Comment by demipixel** [comment]
I can't place roboports that cover the outpost. The best I'll be able to do is place roboports behind the cargo wagons (2 for each cargo wagon, intended for bot based mining).

While I understand that there's more things that could be automated, everybody wants something different. I don't think getting a blueprint to remove repair packs or place storage chests would be too difficult (it's about 4 more clicks when adding an outpost). Other people want loading on both sides or multiple stations per outpost.

I'll keep it open for now, but the last thing I want to do is make the options list unmanageable because it's too long with peoples' individual requests :P

**Comment by tomato42** [comment]
> I can't place roboports that cover the outpost.

why?

> Other people want loading on both sides or multiple stations per outpost.

why not add that option? (I mean, besides time)

> the last thing I want to do is make the options list unmanageable because it's too long with peoples' individual requests

a). it's already aimed at advanced players
b). there can always be a basic view with just the minimum setting (side of train station) and advanced view with all the settings

I mean, you already provide ability to add fully custom load balancer...

**Comment by tomato42** [comment]
(also added to opening comment)

the general idea of resupply does work well together with the gun turrets...

**Comment by demipixel** [comment]
1) No easy way to guarantee when it's large enough. Best I could do is one roboport next to the radar but that wouldn't guarantee full coverage (and likely wouldn't be enough for charging).

2) Time. Also, if for example you have 4 cargo wagons, this is easily achievable by providing an 8 lane balancer and a single blueprint to make the additional 4 lanes go around to the back side.

3) The goal of this is to do 90% of the work. I will *never* be able to add every feature, and there's other automative projects I want to move on to. While I understand having the way "you" do outposts would be more convenient, I want to try to keep the project as generalized as possible. I hope some time in the future to have the possibility of adding other blueprints in similar to the balancer, but I can't imagine manually placing them is too bad for now.

**Comment by tomato42** [comment]
> No easy way to guarantee when it's large enough. Best I could do is one roboport next to the radar but that wouldn't guarantee full coverage

all the stuff in the blueprint is generated by the the script, the coverage of the roboport is a known quantity... Start with the location of the train station, add a roboport at range of logistic network if the far side of the outpost is further than range of the original roboport. Rinse, repeat.

Even for very large outposts, it's a question of essentially going around the perimeter (since you can't put the roboport between the miners, you have to sacrifice some ore for coverage) and then adding roboports in the middle if the perimeter doesn't provide full coverage.

like you said, it's to do the 90% of work. It's quite silly to worry about wasted roboport or two when the goal is to fire a rocket that costs thousands of them...

>  (and likely wouldn't be enough for charging).

it's just for occasional biter attacks, I currently play on regular settings, with my whole base being one big logistic network, and the roboports spaced as sparse as possible while still having logistic links and the bots manage to fix the walls just fine, even when they actually have to haul the repair packs across the whole base and it's fine. Let alone charging being a problem.

> I will never be able to add every feature, and there's other automative projects I want to move on to.

the bug is just a suggestion, if you don't want to do it I can't force you. You've already made an awesome thing. But in case you're Australian, and weary of the looming, long, cold winter nights when there's not much to do... ;)
