### ISSUE TITLE
Left-right possibly mixed up in 0.15.x

### ISSUE THREAD

**Issue by tomato42** [demipixel/factorio-blueprint#13]
I've created a blueprint in 0.15.9 by adding a wall in the top right and bottom right corner.

Exported the blueprint:
```
0eNqNj1ELgkAQhP/LPJ+gYoL3VyJCa4mFc0+8MxPZ/55nPQT10OMsM9/OrOjcRMPIEmFX8MVLgD2uCHyT1qVbXAaCBUfqYSBtn1SIXiibW+egBixXesAWejIgiRyZXpRdLGeZ+o7GzfArbzD4sEW8pG8Js9kW2KzIVc0Xo/yLkb0hjaZOe3f7MdXgTmPY7XVVlYe8acq6Un0CkCBZMA==
```

Used those [settings](http://autotorio.com/?modded=false&belt_type=Transport%20Belt&undergroundBelts=false&trainDirection=Left&minedOreDirection=Top&minerSpace=1&useStackInserters=true&includeRadar=true&botBased=false&requestItem=Iron%20Ore&turretType=Laser%20Turrets&walls=true&includeTrainStation=true&exitRoute=false&locomotiveCount=1&cargoWagonCount=2&concrete=None&borderConcrete=None&trackConcrete=None) (note the Train Station Side "Left") and got an outpost with a train station on the _right_ side of the outpost.

**Comment by demipixel** [comment]
Resolved in next version.
