### ISSUE TITLE
Belts offset near splitters, based-2 snapping of blueprint

### ISSUE THREAD

**Issue by tomato42** [demipixel/factorio-blueprint#14]
![factorio](https://cloud.githubusercontent.com/assets/618246/25820402/6e194f30-3431-11e7-8bda-b2a0c85b0814.jpg)

See #13 on how I've generated the blueprint.

Note the belts under splitters - they are offset half a tile - the splitters are in wrong position too. Weirdly, it places correctly in the world.

The second issue is that I can move the blueprint just two tiles in either direction, can't move it just one tile (to align it better with the ore patch). I'm guessing it is related to the offset splitters so I'm putting it into single issue.

**Comment by demipixel** [comment]
This is an issue with having 2 cargo wagons, and I have yet to figure out the issue. For now, you'll have to manually fix it.

Blueprints with rails can only be moved by 2s so they remain on the rail grid.

**Comment by demipixel** [comment]
Can you test if this still occurs?

**Comment by tomato42** [comment]
Looks to be fixed.

Thanks!
