### ISSUE TITLE
Sometimes encoded blueprints fail to import

### ISSUE THREAD

**Issue by DanielVF** [demipixel/factorio-blueprint#17]
I want to create a duplicate of a blueprint, so that I can make further modifications to it, without messing with the original. I figured the easiest way to do this would be to encode, then import.

    str = orig.encode()
    newBlueprint = new Blueprint(str)

Sometimes however, it fails with a buffer error:

![image](https://user-images.githubusercontent.com/837/26977215-05cf1c2a-4cf5-11e7-85f5-ae6ac68fe1cc.png)

Broken string:
    0eJzFnNtu4jAYhN/F14kUO3YOvMpqVYVgtZbAiZJQbYV49w2HjWhXbT0uIy4JhXyE0TCe3+lBrLd72w/OT2J1EK7t/ChWvw5idM++2Z6OTW+9FSvhJrsTifDN7vSoGUe7W2+df053TfvivE2VOCbC+Y39I1bymHz7Fju7cftdare2nQbXpn23tTdvoY6/E2H95CZnL0hfnToRfTfOf9r50/nml6dVIt7EKp/fcOOG+RTnp7JkYfH9fppfNj/lzgfaru/tkLbNesZI5ofeX141n/xwPB+Yhm77tLYvzavrhsvRM+Dbk9/v1na4fu6vPt//nEUYZxyPuuFxfrTDNB/97FrJ9wz6Tgx5GEN9ZjAcBn3DEKgf/Qj9GFw/iqmfIuy700z9lGEMhqmf6oZhGho/9t0wpWu7nT5VcvaeRN2JpEZIKiaJzBCUkooiEZSCiqIQFENFyREUTUXRCEpORTEIiqKiFAiKpKKUuMMV71GKe6FAZltRUSC3LZkoCnLbgooCua2hokBuq6kokNvmVBTIbRUVBXJbSUUp8EXAxV3SD6nyi1XAJa13fs7rrRvavfsBbxm7mPyeN5KoQpaTacnJ4qpGFpRpzqHIs9gl5WPUlEdUE4qqpjywnNBUNeWB9YThqgly7KuyK04UzCHLrrgsUEIuuSxQRC64LFBGNlwWKCRrKouGUnLOZYFisuKyQDlZclmgoHz1OsXJhBry3YrLAvluyWWBfLfgskC+a7gskO9qLgvkuzmVxUC+q7gskO9KLovCVwkquyDJ8NlTs3ltfGs3P14lmBxfJcgqlDeSSYcl9OW6kWZAxgRyXCUlSfMwE9FjyOKBmoroMaQmayqwyViuG0tTgV2GLLmaKiLaDKkep6kios2Qwb4ayRTYZyzXjaSpIrDRkDlZUxGbLoJ/SgiSith7EeyqkUiB2y8qsqACd2DUZD1VuJ6Cf0YIeqpxPQU7auROmizsi9RcPZUyDMNw9VRCnciS6j5Mp+7VipRQK7JkXRYN1IvImkyDDRErMg22a6Mk00DtyJJnWTRQPyINmQZqSJY1B4mmgjqSJZ2xaLCWRJFpsH6a7MUV5MWS7MVVzGyQBhMzHKTBxEwHaTAx40EaTMx8kAYTMyBkwdQxE0IaTMyIkAYTMyOkwWBx+B/Nh92x96rxa2xDXUamweJwTabB4nBFpsHicEmmweJwQabB4rDh0sgMy8OajYMF4pyNg7mxYuNgkZjsxzLD+gmyIcsMcmSyIcsMcmSyIcsMcmSyIcsMcmSyIcsMcmS2IWM39LH9GLunj23H2G19bDfG7uxjm7HUp1v1zzf3r27+nUAiXu0wnk+VHY9/AYXY+ag=

Here's the json of the broken:

{"blueprint":{"icons":[{"signal":{"type":"item","name":"assembling-machine-2"},"index":1},{"signal":{"type":"item","name":"medium-electric-pole"},"index":2}],"entities":[{"name":"assembling-machine-2","position":{"x":-8,"y":3},"direction":0,"type":"input","recipe":"copper-cable","connections":{},"control_behavior":{},"entity_number":1},{"name":"medium-electric-pole","position":{"x":-6,"y":3},"direction":0,"type":"input","connections":{},"control_behavior":{},"entity_number":2},{"name":"inserter","position":{"x":-8,"y":1},"direction":4,"type":"input","connections":{},"control_behavior":{},"entity_number":3},{"name":"inserter","position":{"x":-9,"y":5},"direction":4,"type":"input","connections":{},"control_behavior":{},"entity_number":4},{"name":"assembling-machine-2","position":{"x":-4,"y":3},"direction":0,"type":"input","recipe":"copper-cable","connections":{},"control_behavior":{},"entity_number":5},{"name":"medium-electric-pole","position":{"x":-2,"y":3},"direction":0,"type":"input","connections":{},"control_behavior":{},"entity_number":6},{"name":"inserter","position":{"x":-4,"y":1},"direction":4,"type":"input","connections":{},"control_behavior":{},"entity_number":7},{"name":"inserter","position":{"x":-5,"y":5},"direction":4,"type":"input","connections":{},"control_behavior":{},"entity_number":8},{"name":"transport-belt","position":{"x":-9,"y":0},"direction":2,"type":"input","connections":{},"control_behavior":{},"entity_number":9},{"name":"transport-belt","position":{"x":-8,"y":0},"direction":2,"type":"input","connections":{},"control_behavior":{},"entity_number":10},{"name":"transport-belt","position":{"x":-7,"y":0},"direction":2,"type":"input","connections":{},"control_behavior":{},"entity_number":11},{"name":"transport-belt","position":{"x":-6,"y":0},"direction":2,"type":"input","connections":{},"control_behavior":{},"entity_number":12},{"name":"transport-belt","position":{"x":-5,"y":0},"direction":2,"type":"input","connections":{},"control_behavior":{},"entity_number":13},{"name":"transport-belt","position":{"x":-4,"y":0},"direction":2,"type":"input","connections":{},"control_behavior":{},"entity_number":14},{"name":"transport-belt","position":{"x":-3,"y":0},"direction":2,"type":"input","connections":{},"control_behavior":{},"entity_number":15},{"name":"transport-belt","position":{"x":-2,"y":0},"direction":2,"type":"input","connections":{},"control_behavior":{},"entity_number":16},{"name":"transport-belt","position":{"x":-1,"y":0},"direction":2,"type":"input","connections":{},"control_behavior":{},"entity_number":17},{"name":"transport-belt","position":{"x":-9,"y":6},"direction":6,"type":"input","connections":{},"control_behavior":{},"entity_number":18},{"name":"transport-belt","position":{"x":-8,"y":6},"direction":6,"type":"input","connections":{},"control_behavior":{},"entity_number":19},{"name":"transport-belt","position":{"x":-7,"y":6},"direction":6,"type":"input","connections":{},"control_behavior":{},"entity_number":20},{"name":"transport-belt","position":{"x":-6,"y":6},"direction":6,"type":"input","connections":{},"control_behavior":{},"entity_number":21},{"name":"transport-belt","position":{"x":-5,"y":6},"direction":6,"type":"input","connections":{},"control_behavior":{},"entity_number":22},{"name":"transport-belt","position":{"x":-4,"y":6},"direction":6,"type":"input","connections":{},"control_behavior":{},"entity_number":23},{"name":"transport-belt","position":{"x":-3,"y":6},"direction":6,"type":"input","connections":{},"control_behavior":{},"entity_number":24},{"name":"transport-belt","position":{"x":-2,"y":6},"direction":6,"type":"input","connections":{},"control_behavior":{},"entity_number":25},{"name":"transport-belt","position":{"x":-1,"y":6},"direction":6,"type":"input","connections":{},"control_behavior":{},"entity_number":26},{"name":"assembling-machine-2","position":{"x":-8,"y":-5},"direction":0,"type":"input","recipe":"electronic-circuit","connections":{},"control_behavior":{},"entity_number":27},{"name":"medium-electric-pole","position":{"x":-6,"y":-5},"direction":0,"type":"input","connections":{},"control_behavior":{},"entity_number":28},{"name":"inserter","position":{"x":-8,"y":-7},"direction":4,"type":"input","connections":{},"control_behavior":{},"entity_number":29},{"name":"inserter","position":{"x":-9,"y":-3},"direction":4,"type":"input","connections":{},"control_behavior":{},"entity_number":30},{"name":"assembling-machine-2","position":{"x":-4,"y":-5},"direction":0,"type":"input","recipe":"electronic-circuit","connections":{},"control_behavior":{},"entity_number":31},{"name":"medium-electric-pole","position":{"x":-2,"y":-5},"direction":0,"type":"input","connections":{},"control_behavior":{},"entity_number":32},{"name":"inserter","position":{"x":-4,"y":-7},"direction":4,"type":"input","connections":{},"control_behavior":{},"entity_number":33},{"name":"inserter","position":{"x":-5,"y":-3},"direction":4,"type":"input","connections":{},"control_behavior":{},"entity_number":34},{"name":"transport-belt","position":{"x":-9,"y":-8},"direction":2,"type":"input","connections":{},"control_behavior":{},"entity_number":35},{"name":"transport-belt","position":{"x":-8,"y":-8},"direction":2,"type":"input","connections":{},"control_behavior":{},"entity_number":36},{"name":"transport-belt","position":{"x":-7,"y":-8},"direction":2,"type":"input","connections":{},"control_behavior":{},"entity_number":37},{"name":"transport-belt","position":{"x":-6,"y":-8},"direction":2,"type":"input","connections":{},"control_behavior":{},"entity_number":38},{"name":"transport-belt","position":{"x":-5,"y":-8},"direction":2,"type":"input","connections":{},"control_behavior":{},"entity_number":39},{"name":"transport-belt","position":{"x":-4,"y":-8},"direction":2,"type":"input","connections":{},"control_behavior":{},"entity_number":40},{"name":"transport-belt","position":{"x":-3,"y":-8},"direction":2,"type":"input","connections":{},"control_behavior":{},"entity_number":41},{"name":"transport-belt","position":{"x":-2,"y":-8},"direction":2,"type":"input","connections":{},"control_behavior":{},"entity_number":42},{"name":"transport-belt","position":{"x":-1,"y":-8},"direction":2,"type":"input","connections":{},"control_behavior":{},"entity_number":43},{"name":"transport-belt","position":{"x":-9,"y":-2},"direction":6,"type":"input","connections":{},"control_behavior":{},"entity_number":44},{"name":"transport-belt","position":{"x":-8,"y":-2},"direction":6,"type":"input","connections":{},"control_behavior":{},"entity_number":45},{"name":"transport-belt","position":{"x":-7,"y":-2},"direction":6,"type":"input","connections":{},"control_behavior":{},"entity_number":46},{"name":"transport-belt","position":{"x":-6,"y":-2},"direction":6,"type":"input","connections":{},"control_behavior":{},"entity_number":47},{"name":"transport-belt","position":{"x":-5,"y":-2},"direction":6,"type":"input","connections":{},"control_behavior":{},"entity_number":48},{"name":"transport-belt","position":{"x":-4,"y":-2},"direction":6,"type":"input","connections":{},"control_behavior":{},"entity_number":49},{"name":"transport-belt","position":{"x":-3,"y":-2},"direction":6,"type":"input","connections":{},"control_behavior":{},"entity_number":50},{"name":"transport-belt","position":{"x":-2,"y":-2},"direction":6,"type":"input","connections":{},"control_behavior":{},"entity_number":51},{"name":"transport-belt","position":{"x":-1,"y":-2},"direction":6,"type":"input","connections":{},"control_behavior":{},"entity_number":52},{"name":"assembling-machine-2","position":{"x":-20,"y":-13},"direction":0,"type":"input","recipe":"advanced-circuit","connections":{},"control_behavior":{},"entity_number":53},{"name":"medium-electric-pole","position":{"x":-18,"y":-13},"direction":0,"type":"input","connections":{},"control_behavior":{},"entity_number":54},{"name":"inserter","position":{"x":-20,"y":-15},"direction":4,"type":"input","connections":{},"control_behavior":{},"entity_number":55},{"name":"inserter","position":{"x":-21,"y":-11},"direction":4,"type":"input","connections":{},"control_behavior":{},"entity_number":56},{"name":"assembling-machine-2","position":{"x":-16,"y":-13},"direction":0,"type":"input","recipe":"advanced-circuit","connections":{},"control_behavior":{},"entity_number":57},{"name":"medium-electric-pole","position":{"x":-14,"y":-13},"direction":0,"type":"input","connections":{},"control_behavior":{},"entity_number":58},{"name":"inserter","position":{"x":-16,"y":-15},"direction":4,"type":"input","connections":{},"control_behavior":{},"entity_number":59},{"name":"inserter","position":{"x":-17,"y":-11},"direction":4,"type":"input","connections":{},"control_behavior":{},"entity_number":60},{"name":"assembling-machine-2","position":{"x":-12,"y":-13},"direction":0,"type":"input","recipe":"advanced-circuit","connections":{},"control_behavior":{},"entity_number":61},{"name":"medium-electric-pole","position":{"x":-10,"y":-13},"direction":0,"type":"input","connections":{},"control_behavior":{},"entity_number":62},{"name":"inserter","position":{"x":-12,"y":-15},"direction":4,"type":"input","connections":{},"control_behavior":{},"entity_number":63},{"name":"inserter","position":{"x":-13,"y":-11},"direction":4,"type":"input","connections":{},"control_behavior":{},"entity_number":64},{"name":"assembling-machine-2","position":{"x":-8,"y":-13},"direction":0,"type":"input","recipe":"advanced-circuit","connections":{},"control_behavior":{},"entity_number":65},{"name":"medium-electric-pole","position":{"x":-6,"y":-13},"direction":0,"type":"input","connections":{},"control_behavior":{},"entity_number":66},{"name":"inserter","position":{"x":-8,"y":-15},"direction":4,"type":"input","connections":{},"control_behavior":{},"entity_number":67},{"name":"inserter","position":{"x":-9,"y":-11},"direction":4,"type":"input","connections":{},"control_behavior":{},"entity_number":68},{"name":"assembling-machine-2","position":{"x":-4,"y":-13},"direction":0,"type":"input","recipe":"advanced-circuit","connections":{},"control_behavior":{},"entity_number":69},{"name":"medium-electric-pole","position":{"x":-2,"y":-13},"direction":0,"type":"input","connections":{},"control_behavior":{},"entity_number":70},{"name":"inserter","position":{"x":-4,"y":-15},"direction":4,"type":"input","connections":{},"control_behavior":{},"entity_number":71},{"name":"inserter","position":{"x":-5,"y":-11},"direction":4,"type":"input","connections":{},"control_behavior":{},"entity_number":72},{"name":"transport-belt","position":{"x":-21,"y":-16},"direction":2,"type":"input","connections":{},"control_behavior":{},"entity_number":73},{"name":"transport-belt","position":{"x":-20,"y":-16},"direction":2,"type":"input","connections":{},"control_behavior":{},"entity_number":74},{"name":"transport-belt","position":{"x":-19,"y":-16},"direction":2,"type":"input","connections":{},"control_behavior":{},"entity_number":75},{"name":"transport-belt","position":{"x":-18,"y":-16},"direction":2,"type":"input","connections":{},"control_behavior":{},"entity_number":76},{"name":"transport-belt","position":{"x":-17,"y":-16},"direction":2,"type":"input","connections":{},"control_behavior":{},"entity_number":77},{"name":"transport-belt","position":{"x":-16,"y":-16},"direction":2,"type":"input","connections":{},"control_behavior":{},"entity_number":78},{"name":"transport-belt","position":{"x":-15,"y":-16},"direction":2,"type":"input","connections":{},"control_behavior":{},"entity_number":79},{"name":"transport-belt","position":{"x":-14,"y":-16},"direction":2,"type":"input","connections":{},"control_behavior":{},"entity_number":80},{"name":"transport-belt","position":{"x":-13,"y":-16},"direction":2,"type":"input","connections":{},"control_behavior":{},"entity_number":81},{"name":"transport-belt","position":{"x":-12,"y":-16},"direction":2,"type":"input","connections":{},"control_behavior":{},"entity_number":82},{"name":"transport-belt","position":{"x":-11,"y":-16},"direction":2,"type":"input","connections":{},"control_behavior":{},"entity_number":83},{"name":"transport-belt","position":{"x":-10,"y":-16},"direction":2,"type":"input","connections":{},"control_behavior":{},"entity_number":84},{"name":"transport-belt","position":{"x":-9,"y":-16},"direction":2,"type":"input","connections":{},"control_behavior":{},"entity_number":85},{"name":"transport-belt","position":{"x":-8,"y":-16},"direction":2,"type":"input","connections":{},"control_behavior":{},"entity_number":86},{"name":"transport-belt","position":{"x":-7,"y":-16},"direction":2,"type":"input","connections":{},"control_behavior":{},"entity_number":87},{"name":"transport-belt","position":{"x":-6,"y":-16},"direction":2,"type":"input","connections":{},"control_behavior":{},"entity_number":88},{"name":"transport-belt","position":{"x":-5,"y":-16},"direction":2,"type":"input","connections":{},"control_behavior":{},"entity_number":89},{"name":"transport-belt","position":{"x":-4,"y":-16},"direction":2,"type":"input","connections":{},"control_behavior":{},"entity_number":90},{"name":"transport-belt","position":{"x":-3,"y":-16},"direction":2,"type":"input","connections":{},"control_behavior":{},"entity_number":91},{"name":"transport-belt","position":{"x":-2,"y":-16},"direction":2,"type":"input","connections":{},"control_behavior":{},"entity_number":92},{"name":"transport-belt","position":{"x":-1,"y":-16},"direction":2,"type":"input","connections":{},"control_behavior":{},"entity_number":93},{"name":"transport-belt","position":{"x":-21,"y":-10},"direction":6,"type":"input","connections":{},"control_behavior":{},"entity_number":94},{"name":"transport-belt","position":{"x":-20,"y":-10},"direction":6,"type":"input","connections":{},"control_behavior":{},"entity_number":95},{"name":"transport-belt","position":{"x":-19,"y":-10},"direction":6,"type":"input","connections":{},"control_behavior":{},"entity_number":96},{"name":"transport-belt","position":{"x":-18,"y":-10},"direction":6,"type":"input","connections":{},"control_behavior":{},"entity_number":97},{"name":"transport-belt","position":{"x":-17,"y":-10},"direction":6,"type":"input","connections":{},"control_behavior":{},"entity_number":98},{"name":"transport-belt","position":{"x":-16,"y":-10},"direction":6,"type":"input","connections":{},"control_behavior":{},"entity_number":99},{"name":"transport-belt","position":{"x":-15,"y":-10},"direction":6,"type":"input","connections":{},"control_behavior":{},"entity_number":100},{"name":"transport-belt","position":{"x":-14,"y":-10},"direction":6,"type":"input","connections":{},"control_behavior":{},"entity_number":101},{"name":"transport-belt","position":{"x":-13,"y":-10},"direction":6,"type":"input","connections":{},"control_behavior":{},"entity_number":102},{"name":"transport-belt","position":{"x":-12,"y":-10},"direction":6,"type":"input","connections":{},"control_behavior":{},"entity_number":103},{"name":"transport-belt","position":{"x":-11,"y":-10},"direction":6,"type":"input","connections":{},"control_behavior":{},"entity_number":104},{"name":"transport-belt","position":{"x":-10,"y":-10},"direction":6,"type":"input","connections":{},"control_behavior":{},"entity_number":105},{"name":"transport-belt","position":{"x":-9,"y":-10},"direction":6,"type":"input","connections":{},"control_behavior":{},"entity_number":106},{"name":"transport-belt","position":{"x":-8,"y":-10},"direction":6,"type":"input","connections":{},"control_behavior":{},"entity_number":107},{"name":"transport-belt","position":{"x":-7,"y":-10},"direction":6,"type":"input","connections":{},"control_behavior":{},"entity_number":108},{"name":"transport-belt","position":{"x":-6,"y":-10},"direction":6,"type":"input","connections":{},"control_behavior":{},"entity_number":109},{"name":"transport-belt","position":{"x":-5,"y":-10},"direction":6,"type":"input","connections":{},"control_behavior":{},"entity_number":110},{"name":"transport-belt","position":{"x":-4,"y":-10},"direction":6,"type":"input","connections":{},"control_behavior":{},"entity_number":111},{"name":"transport-belt","position":{"x":-3,"y":-10},"direction":6,"type":"input","connections":{},"control_behavior":{},"entity_number":112},{"name":"transport-belt","position":{"x":-2,"y":-10},"direction":6,"type":"input","connections":{},"control_behavior":{},"entity_number":113},{"name":"transport-belt","position":{"x":-1,"y":-10},"direction":6,"type":"input","connections":{},"control_behavior":{},"entity_number":114}],"item":"blueprint","version":0}}

Just a few less of the same buildings, but works:

0eJzF2u9uokAUBfB3mc+QMMMwgK+y2TSIk3YSGAigWWN898U/a7SbtpypJ/0oFviJt4c7Vw5i3WxtPzg/idVBuLrzo1j9OojRvfqqOW2b9r0VK+Em24pI+Ko9varG0bbrxvnXuK3qN+dtrMQxEs5v7B+xksfoy0O0duO2bWwbW0+Dq+O+a+zdIdTxdySsn9zk7IX02akj0Xfj/KedP51v3j0uIrEXq3Q+4MYN8ynObyXRzeL77TTvNr/lzhvqru/tENfVemZE80vvL3vNJz8czxumoWte1vat2rluuGw9A/cvftuu7XD93J99vv+dZpkzzKPuPM6PdpjmrR9dK/lo0E8ypMsM5dmQcQz6zrCwfvRP1E+G149i1o9Z9t1pZv3kywwZs36KO8M0VH7su2GK17aZPqzk5FGiniQpEUnBlMgEoeRUikQohkpRCCWjUlKEoqkUjVBSKiVDKIpKMQhFUik5nnDmkWKeRYHCtqBSoLTNmRQFpa2hUqC0zagUKG01lQKlbUqlQGmrqBQobSWVYkIXAfG7rvKTVcClW+/83K/Xbqi37hvePHQx8LU3UFQgy4E45/TiqkQWBHHKUaRQHl8tBefmnUKBrLkWKJFTrgWKZMW1QJksuRYolK+1qzipnEI9sOZaoCY45VqgLlhxLVAbLKkWneB3cXm9PHL5NK/a7Cpf28237+I6YCQsk6XeQNPCsfDturGmsgtHw/L6ryZJE0YdMB4ufrCkAqbEhlxRCwfFBbmgFs6KS3I9FcErjR+ppzJ4ocGqpyyBVhqsesoktNRg1VMG9dS3tHy3jn5W95hBXfXtHsLSYH21JGuwcUdC1kC9dUnGQM11QcZA3XVOxkDtteFiTMhcg4YJGWzQMCGTDRomZLRBw4TMNmgYLIL/fU/vfld71nLVYD/xKbIGyuDbzZKlgUL4drNkaaAULrmYHErhgoyBUjgnY6AUNmQMlMIZGQOlsCZjoBQmh3AOhTA5g3Msg8mY4vSU7fm53NXdk8CR2NlhvKzoj8e/POsUvw==

**Comment by demipixel** [comment]
Where are you doing this? If this is on the Autotorio site, I recommend just exporting to data and reimporting (I believe it's `new Blueprint(bp.getData())` or something like that) and I'll have to look into this issue.

If you're converting this to browser code on your own, there appears to be an issue with the zlib library with browserify that causes errors like this. Look into Autotorio's `scripts/postinstall.js` for how I got around the issue.

**Comment by DanielVF** [comment]
Thanks. Yes, it's having a problem in the browser.

I'm working making my own browser/node based blueprint builder. Tell it that you want Y per second of X, and it builds a blueprint that makes that and all it's dependencies.

Looking at the [script](https://github.com/demipixel/autotorio/blob/master/scripts/postinstall.js) - looks like you are alaising in a different zlib?

**Comment by demipixel** [comment]
Yep, so the current zlib browserify has some bugs in it, so I had to use an alternate version...

*However*, I had to fork the github because it would not build with my postinstall.js script correctly, so feel free to use that fork.

The thing in post-install just makes sure instead of using browserify's zlib it uses the custom one

**Comment by DanielVF** [comment]
Gotcha.

I'm going to close this one - it's not really your problem, and I'll just not reimport the blueprint.

**Comment by demipixel** [comment]
This seems to be specific to browserify, however. Like I said, if you want to duplicate a blueprint, I recommend the .getData() method, that's the best way to "reimport".

**Comment by DanielVF** [comment]
Thanks! That makes sense.
