### ISSUE TITLE
steam does not exist! You can add it by putting it into entityData.

### ISSUE THREAD

**Issue by acbabis** [demipixel/factorio-blueprint#20]
Water, crude_oil, petroleum_gas, heavy_oil, light_oil, sulfuric_acid, and lubricant are all present, but steam is not. It might be as simple as adding it [here](https://github.com/demipixel/factorio-blueprint/blob/56562f32b0b33d722341fabbb032628e06fab3db/defaultentities.js#L616), but I'm not sure.

**Comment by demipixel** [comment]
Thanks!
