### ISSUE TITLE
Are coordinates reversed?

### ISSUE THREAD

**Issue by captncraig** [demipixel/factorio-blueprint#3]
Hey, I love this tool. I was trying to build some things and had to dig to discover how to set "position" for `createEntity`. It looks like it expects a Victor vector, which I can make. I'm having trouble figuring out exactly how the coordinates relate to factorio coordinates though. Here is what I am testing:

```
const Blueprint = require('factorio-blueprint')
const Victor = require('victor');

var bp = new Blueprint();
bp.createEntity("medium_electric_pole", new Victor(0,0))
bp.createEntity("small_lamp", new Victor(-1,0))
bp.createEntity("small_lamp", new Victor(-1,-2))

console.log(bp.toString());
console.log(bp.luaString());
console.log(bp.encode());
```

In factorio x increases to the right, and y increases downward. I expect the pattern on the left, but get the pattern on the right. Are x and y reversed, or am I using this wrong?

![screen shot 2016-05-21 at 12 29 42 am](https://cloud.githubusercontent.com/assets/192540/15446903/62c4a19a-1eeb-11e6-8c3f-d175af4260e0.png)

**Comment by demipixel** [comment]
Aha, shows how much I tested this thing—I was just using it for FactorioScript. Lemme look into this.

**Comment by demipixel** [comment]
It's possible it's the direction. Just curious, what are those west/north variables? They're suppose to be used for rotation which wouldn't normally matter for electric poles or lamps (although this bug should still be fixed).

**Comment by captncraig** [comment]
I was playing with belts initially, but switched those out for entities already defined. thats where the directions came in

**Comment by captncraig** [comment]
simplified code

**Comment by captncraig** [comment]
Oh, perhaps I had simply rotated it in game. That actually makes sense now.

**Comment by demipixel** [comment]
Ahaha, you want to confirm that? That's great :P

**Comment by captncraig** [comment]
Yeah, if I use a belt as a marker and orient it so it is moving up, an then place the blueprint, it is exactly what I expect. Sorry to bug you over nothing.

**Comment by demipixel** [comment]
For some reason Factorio will randomly rotate blueprints (or maybe it's the blueprint mod). We shall see if this gets fixed...
