### ISSUE TITLE
How to use "toBook"

### ISSUE THREAD

**Issue by Opsse** [demipixel/factorio-blueprint#40]
I'm trying to create a book from several blueprints.
The [toBook](https://demipixel.github.io/factorio-blueprint/#/classes/Blueprint?id=static-blueprinttobookblueprints-activeindex0-versionquotlatestquot) function seems to do what I want. But I don't have the expected result.

With this code :
```javascript
const Blueprint = require('factorio-blueprint');

// Create a blueprint with nothing in it
const myBlueprint = new Blueprint();
const myBlueprint2 = new Blueprint();

// Modify the blueprint!
myBlueprint.createEntity('transport-belt', { x: 0, y: 0 }, Blueprint.UP);
myBlueprint2.createEntity('transport-belt', { x: 1, y: 1 }, Blueprint.UP);

// Export the string to use in-game
console.log(Blueprint.toBook([myBlueprint, myBlueprint2]));
```
I get :
> undefined

Is it a bug or I misunderstand the documentation?

My current script with a temporary fix is [here](https://github.com/Opsse/Factorio-Lego/blob/master/books_maker.js). With this one I get the book string, but in game I have some errors during importing (I can post them later if necessary).

Bonus question : Is it possible to set the name of the book?

**Comment by demipixel** [comment]
This is a bug, will be an easy fix.

**Comment by demipixel** [comment]
Resolved. As of right now, we don't support book names (was that always a thing? I figured we would have added it). I think it should be simple enough to add.
