### ISSUE TITLE
Regexp doesn't match named blueprints.

### ISSUE THREAD

**Issue by FactorioBlueprints** [demipixel/factorio-blueprint#8]
```javascript
    const match = converted.match(/do local _={entities={(.+)},icons={(.+)}};return _;end/);
    if (!match) throw new Error('Invalid blueprint string');
```
This regular expression assumes a blueprint has two main sections, entities and icons. There can be a third section called name right after icons like this:

```
icons={{signal={type="item",name="transport-belt"},index=1},{signal={type="item",name="steel-furnace"},index=2}},name="Example blueprint name"};return _;end"
```

Updating the regex will match more valid blueprints without messing up the icons section, and it would be nice to store the name when it's available and expose it through api.

**Comment by FactorioBlueprints** [comment]
I believe the regex should look like this.

```javascript
const match = converted.match(/do local _={entities={(.+)},icons={(.+)}(,name="(.+)")?};return _;end/);
```

That would put the name into group 4 if it exists.

**Comment by demipixel** [comment]
Sorry for the late fix, didn't see the email.
